max_error: 0.01
skip_points: 0
use_end_conditions: false
use_middle_conditions: false

path_poses:
  - { x: 4.0, y: 0.0 }
  - { x: 2.5, y: -2.0 }
  - { x: 1.0, y: -2.0 }
  - { x: 0.0, y: -2.0 }
  - { x: -1.0, y: -2.0 }
  - { x: -2.5, y: -2.0 }
  - { x: -4.0, y: 0.0 }
  - { x: -2.5, y: 2.0 }
  - { x: -1.0, y: 2.0 }
  - { x: 0.0, y: 2.0 }
  - { x: 1.0, y: 2.0 }
  - { x: 2.5, y: 2.0 }
  - { x: 4.0, y: 0.0 }

